---
title: "About Us"
subtitle: ""
---

## Our Mission

To advance knowledge and expand capacity in the field of infectious disease modelling and data analytics, by collaborating, innovating, and training, with the goal of being prepared for pandemics in the Netherlands.

## Our Vision

-	Train and expand capacity by empowering a next generation of researchers to fulfill their professional potential in infectious disease modelling and data analytics in a setting that is welcoming and inclusive.

-	Create a professional network with connections between and among different scientific disciplines to share and exchange knowledge, to innovate, and to accelerate progress in the science behind controlling the spread of infections and develop visibility of the field.

-	Support infrastructure and coordinate a dynamic capacity dedicated to collaboration, innovative research, teaching, mentoring such as to be prepared for trusted advice, in a transparent way, for policy makers in the field of  infectious disease control during times of crisis.

## Partner Organizations

CODEMAP includes professionals working at a range of institutions in the Netherlands and abroad. Below is a list of participating institutions. For more details, see our [Members page](members/index.qmd){.btn .btn-primary}

- Universiteit Utrecht (UU) 
- Wageningen University and Research (WUR) 
- Erasmus MC 
- Radboud UMC 
- TU Eindhoven 
- TU Delft 
- TNO 
- Vrije Universiteit (VU) 
- Universitair Medisch Centrum Utrecht (UMCU) 
- Leiden Universitair Medisch Centrum (LUMC) 
- Amsterdam UMC 
- Universiteit Twente 
- Tilburg Universiteit 
- Rijksuniversiteit Groningen (RUG) 
- Universiteit van Amsterdam (UvA) 
- Centraal Bureau voor de Statistiek (CBS) 
- Sociaal en Cultureel Planbureau (SCP)
- Landelijk Coördinatie Centrum Patiëntenspreiding (LCPS)
- London School of Hygiene and Tropical Medicine (LSHTM) 
- VWS
- RIVM


<!-- \[Get Started\](learn/index.qmd){.btn .btn-primary} -->
<!-- \[Contact Us\](contact.qmd){.btn .btn-outline} -->
