---
title: "Events"
format: html
---

## Upcoming Events

- **29 May 2026:** Workshop on Pandemic Strategies in Schools

- **19 June 2026:** Symposium Connecting Survival Analysis and Infectious Disease Modelling, 
  - **Location:** Gorlaeus Building in the Leiden Bio Science Park

<!-- Perfect for complete beginners! Learn Python basics in a hands-on workshop. -->

<!-- [Register Now](#){.btn .btn-primary} -->

## Past Events

- **29 May 2026:** Workshop on Pandemic Strategies in Schools

- **9 March 2026:** Meeting on HIV, mpox and STI Modelling

- **12 December 2025:** Infectious Disease Models in Crisis Decision-Making: Roles, Pathways, and Realities in the Policy Arena, (Organised at VWS)

- **31 October 2025:** Phaeton Workshop, TNO Leiden

- **3 March 2025:** Mpox and HIV/STI Modelling meeting

- **13-14 February 2025:** The Future of Nowcasting Infectious Diseases 

-	**22 November 2024:** Towards capturing human mobility in infectious disease models for pandemic preparedness and control (organized with the R2M2P2 project, Erasmus MC)

- **6 June 2024:** Overview of COVID-19 modelling effort in the Netherlands: effectiveness of measures

-	**8 April 2024:** Mpox and HIV/STI Modelling meeting 

<!-- ## Event Calendar -->

<!-- ```{=html} -->
<!-- <div id="calendar"></div> -->
<!-- <script> -->
<!-- // Add calendar integration here -->
<!-- </script> -->
<!-- ``` -->
